# AfkPool Config File

region-name: afk # WorldGuard region name here (def: afk)
crate-name: afk # Crate name here

# Minecraft tps is (by default) 20 ticks per second
# so multiply the seconds of the time frame you want
# by 20 to get the ticks of it.

money-interval: 1200 # Interval of money in ticks (def: 1200) which is 1 minute 
crate-interval: 24000 # Interval of crates in ticks (def: 24000) which is 20 minutes

# Now the commands the plugin is going to execute

# By default command 1 is the money command
# and command 2 is the crate command

# But you can set this to whatever you want!

# %p is the player
# %m is the amount of random number
# %c is the crates name

command-1: eco give %p %m
command-2: cc give physical %c 1 %p

# This value is the subtitle of the title that is given ( the little text under the title)

subtitle: Given By AfkPool

# OK let me tell you how to use integers 1 and 2, so the default is 50 - 100 money, so in java it would
# look like this `(Math.random() * 51 (int 1) ) + 50 (int2);`, so both of the numbers add to 101 which is 1 above 100
# (because it is inclusive) so If you want to do 1 - 50 (which added is 51) it should be
 
# integer-1: 50
# integer-2: 1

integer-1: 51
integer-2: 50

# Figure it out yourself I gave a basic example of what you need to do.




#Made by Abdullah :)

# ██╗░░░██╗░█████╗░██████╗░██████╗░██╗░░░██╗██╗░░░░░██╗░░░░░  ███╗░░░███╗░█████╗░
# ██║░░░██║██╔══██╗██╔══██╗██╔══██╗██║░░░██║██║░░░░░██║░░░░░  ████╗░████║██╔══██╗
# ╚██╗░██╔╝██║░░██║██████╔╝██████╦╝██║░░░██║██║░░░░░██║░░░░░  ██╔████╔██║██║░░╚═╝
# ░╚████╔╝░██║░░██║██╔══██╗██╔══██╗██║░░░██║██║░░░░░██║░░░░░  ██║╚██╔╝██║██║░░██╗
# ░░╚██╔╝░░╚█████╔╝██║░░██║██████╦╝╚██████╔╝███████╗███████╗  ██║░╚═╝░██║╚█████╔╝
# ░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚═════╝░░╚═════╝░╚══════╝╚══════╝  ╚═╝░░░░░╚═╝░╚════╝░