# AfkPool Config File

region-name: afk # WorldGuard region name here (def: afk) (cAsE sEnSiTiVe)
crate-name: afk # Crate name here (cAsE sEnSiTiVe)

# Minecraft tps is (by default) 20 ticks per second
# so multiply the seconds of the time frame you want
# by 20 to get the ticks of it.

command1-interval: 1200 # Interval of money (or whatever you set) in ticks (def: 1200) which is 1 minute 
command2-interval: 24000 # Interval of crates in ticks (def: 24000) which is 20 minutes

# Ok now we have that done lets do the true/false booleans

command-1-enabled: true
command-2-enabled: true

# You get the idea.

# Now the commands the plugin is going to execute

# By default command 1 is the money command
# and command 2 is the crate command

# But you can set this to whatever you want!

# %p is the player
# %m is the amount of random number
# %c is the crates name

command-1: eco give %p %m
command-2: cc give physical %c 1 %p

# Titles, these values are the values of the titles
# %m is the amount of random number
# %c is the crates name

command1-title: You Have been given &a$%m
command2-title: You Have been given an &e%c &fCrate key
entering-title: You have &aentered &fthe &3Afk &fPool
exiting-title: You have &4left &fthe &3Afk &fPool

# This value is the subtitle of the title that is given ( the little text under the title)

subtitle: Given By AfkPool

# Numbers!, these values are the values of the minimum and maximum numbers.
# eg. the comment below is for 1 - 50
 
# min: 1
# max: 50

min: 50
max: 100

# Made by Abdullah :)

# ██╗░░░██╗░█████╗░██████╗░██████╗░██╗░░░██╗██╗░░░░░██╗░░░░░  ███╗░░░███╗░█████╗░
# ██║░░░██║██╔══██╗██╔══██╗██╔══██╗██║░░░██║██║░░░░░██║░░░░░  ████╗ ░████║██╔══██╗
# ╚██╗░██╔╝██║░░██║██████╔╝██████╦╝██║░░░██║██║░░░░░██║░░░░░  ██╔████╔██║██║░░╚═╝
# ░╚████╔╝░██║░░██║██╔══██╗██╔══██╗██║░░░██║██║░░░░░██║░░░░░  ██║╚██╔╝██║██║░░██╗
# ░░╚██╔╝░░╚█████╔╝██║░░██║██████╦╝╚██████╔╝███████╗███████╗  ██║░╚═╝░██║╚█████╔╝
# ░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚═════╝░░╚═════╝░╚══════╝╚══════╝  ╚═╝░░░░░╚═╝░╚════╝░