name: PluginDemo
main: com.abdullaharafat.AfkPool.App
description: A plugin that rewards AFK players in a specific region
version: ${project.version}
api-version: 1.19
depend: [WorldGuard,EssentialsX]