name: AfkPool
api: []
main: com.abdullaharafat.AfkPool.App
description: A plugin that rewards AFK players in a specific region
version: ${project.version}
api-version: 1.13
depend: [WorldGuard]
commands:
  AfkPool:
    description: Triggers events with in AfkPool and shows the values, permission is afkpool.use
    usage: /AfkPool <help|reload|test|values>
    permission: afkpool.use
  ap:
    description: A shortcut to the AfkPool command
    usage: /ap <help|reload|test|values>
    permission: afkpool.use
