name: AfkPool
main: com.abdullaharafat.AfkPool.App
description: A plugin that rewards AFK players in a specific region
version: 1.1.9
api-version: 1.19
depend: [WorldGuard]
commands:
  AfkPool:
    description: Rewards players for being AFK in a specific region
    usage: /AfkPool <help|reload|test|values>
    permission: afkpool.use