name: Build AfkPool JAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 20.0.1
    
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AfkPool-jar
        path: target/*.jar
